# Generated by Django 6.0.6 on 2026-06-28 04:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('exchange', models.CharField(default='NSE', max_length=10)),
                ('sector', models.CharField(max_length=60)),
                ('ltp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField(default=0)),
                ('market_cap_cr', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('pe', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('eps', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('week52_high', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('week52_low', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('roe', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('debt_to_equity', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('revenue_growth', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='OptionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underlying', models.CharField(db_index=True, max_length=20)),
                ('strike', models.DecimalField(decimal_places=2, max_digits=12)),
                ('option_type', models.CharField(choices=[('CE', 'Call'), ('PE', 'Put')], max_length=2)),
                ('ltp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('oi', models.BigIntegerField(default=0)),
                ('volume', models.BigIntegerField(default=0)),
                ('expiry', models.DateField()),
            ],
            options={
                'indexes': [models.Index(fields=['underlying', 'expiry'], name='stocks_opti_underly_66c226_idx')],
            },
        ),
        migrations.CreateModel(
            name='SipPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installments_done', models.PositiveIntegerField(default=0)),
                ('total_installments', models.PositiveIntegerField(default=12)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('next_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sip_plans', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('condition', models.CharField(choices=[('above', 'Above'), ('below', 'Below')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Executed', 'Executed'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Executed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_trades', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DividendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_share', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ex_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('shares_held', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Paid', 'Paid')], default='Upcoming', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('source', models.CharField(max_length=80)),
                ('published_at', models.DateTimeField()),
                ('related_symbols', models.JSONField(default=list)),
                ('category', models.CharField(default='market', max_length=40)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='stocks.stock')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField(default=0)),
                ('interval', models.CharField(choices=[('5m', '5 Minutes'), ('1h', '1 Hour'), ('1d', '1 Day')], default='1d', max_length=5)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='stocks.stock')),
            ],
            options={
                'ordering': ['time'],
                'indexes': [models.Index(fields=['stock', 'interval', 'time'], name='stocks_stoc_stock_i_b3e2e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'stock')},
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
