from datetime import timedelta
from decimal import Decimal

from django.db import migrations, models
from django.utils import timezone


def seed_ipo_events(apps, schema_editor):
    IpoEvent = apps.get_model('stocks', 'IpoEvent')
    today = timezone.localdate()

    rows = [
        {
            'id': 'ipo-nova-retail',
            'company_name': 'Nova Retail Ltd',
            'symbol': 'NOVA',
            'sector': 'Consumer Retail',
            'status': 'open',
            'open_date': today,
            'close_date': today + timedelta(days=2),
            'listing_date': today + timedelta(days=9),
            'price_band_min': Decimal('118'),
            'price_band_max': Decimal('125'),
            'issue_size_cr': Decimal('850.00'),
            'lot_size': 120,
            'min_investment': Decimal('15000'),
            'gmp_percent': Decimal('22.5'),
            'subscription_times': '4.2x',
            'exchange': 'NSE',
            'is_featured': True,
            'description': 'Omnichannel retail chain expanding across Tier-2 cities.',
        },
        {
            'id': 'ipo-greengrid-power',
            'company_name': 'GreenGrid Power Ltd',
            'symbol': 'GGRID',
            'sector': 'Renewable Energy',
            'status': 'open',
            'open_date': today - timedelta(days=1),
            'close_date': today + timedelta(days=1),
            'listing_date': today + timedelta(days=8),
            'price_band_min': Decimal('210'),
            'price_band_max': Decimal('221'),
            'issue_size_cr': Decimal('1200.00'),
            'lot_size': 68,
            'min_investment': Decimal('15028'),
            'gmp_percent': Decimal('18.0'),
            'subscription_times': '6.8x',
            'exchange': 'NSE',
            'is_featured': True,
            'description': 'Solar and wind IPP operator with 1.2 GW operational capacity.',
        },
        {
            'id': 'ipo-skyline-logistics',
            'company_name': 'Skyline Logistics Ltd',
            'symbol': 'SKYLOG',
            'sector': 'Logistics',
            'status': 'upcoming',
            'open_date': today + timedelta(days=5),
            'close_date': today + timedelta(days=7),
            'listing_date': today + timedelta(days=14),
            'price_band_min': Decimal('95'),
            'price_band_max': Decimal('100'),
            'issue_size_cr': Decimal('620.00'),
            'lot_size': 150,
            'min_investment': Decimal('15000'),
            'gmp_percent': Decimal('12.0'),
            'subscription_times': '',
            'exchange': 'NSE',
            'is_featured': True,
            'description': 'Express freight and last-mile delivery network.',
        },
        {
            'id': 'ipo-auratech-solutions',
            'company_name': 'AuraTech Solutions Ltd',
            'symbol': 'AURAT',
            'sector': 'IT Services',
            'status': 'upcoming',
            'open_date': today + timedelta(days=10),
            'close_date': today + timedelta(days=12),
            'listing_date': today + timedelta(days=19),
            'price_band_min': Decimal('450'),
            'price_band_max': Decimal('475'),
            'issue_size_cr': Decimal('980.00'),
            'lot_size': 31,
            'min_investment': Decimal('14725'),
            'gmp_percent': Decimal('8.5'),
            'subscription_times': '',
            'exchange': 'NSE',
            'is_featured': False,
            'description': 'Cloud-native enterprise software and AI services.',
        },
        {
            'id': 'ipo-metro-healthcare',
            'company_name': 'Metro Healthcare Ltd',
            'symbol': 'METROH',
            'sector': 'Healthcare',
            'status': 'upcoming',
            'open_date': today + timedelta(days=14),
            'close_date': today + timedelta(days=16),
            'listing_date': today + timedelta(days=23),
            'price_band_min': Decimal('330'),
            'price_band_max': Decimal('347'),
            'issue_size_cr': Decimal('740.00'),
            'lot_size': 43,
            'min_investment': Decimal('14921'),
            'gmp_percent': Decimal('15.0'),
            'subscription_times': '',
            'exchange': 'NSE',
            'is_featured': False,
            'description': 'Multi-specialty hospital chain in western India.',
        },
        {
            'id': 'ipo-pixel-games',
            'company_name': 'Pixel Games Studio Ltd',
            'symbol': 'PIXEL',
            'sector': 'Media & Entertainment',
            'status': 'closed',
            'open_date': today - timedelta(days=10),
            'close_date': today - timedelta(days=8),
            'listing_date': today + timedelta(days=2),
            'price_band_min': Decimal('280'),
            'price_band_max': Decimal('295'),
            'issue_size_cr': Decimal('510.00'),
            'lot_size': 50,
            'min_investment': Decimal('14750'),
            'gmp_percent': Decimal('32.0'),
            'subscription_times': '12.4x',
            'exchange': 'NSE',
            'is_featured': False,
            'description': 'Mobile gaming studio with global publishing partners.',
        },
        {
            'id': 'ipo-harbor-infra',
            'company_name': 'Harbor Infra Projects Ltd',
            'symbol': 'HARBOR',
            'sector': 'Infrastructure',
            'status': 'listed',
            'open_date': today - timedelta(days=35),
            'close_date': today - timedelta(days=33),
            'listing_date': today - timedelta(days=20),
            'price_band_min': Decimal('165'),
            'price_band_max': Decimal('174'),
            'issue_size_cr': Decimal('1100.00'),
            'lot_size': 86,
            'min_investment': Decimal('14964'),
            'gmp_percent': Decimal('28.0'),
            'subscription_times': '18.6x',
            'exchange': 'NSE',
            'is_featured': False,
            'description': 'Roads, ports, and urban infra EPC contractor.',
        },
        {
            'id': 'ipo-freshbite-foods',
            'company_name': 'FreshBite Foods Ltd',
            'symbol': 'FRESH',
            'sector': 'FMCG',
            'status': 'listed',
            'open_date': today - timedelta(days=50),
            'close_date': today - timedelta(days=48),
            'listing_date': today - timedelta(days=35),
            'price_band_min': Decimal('142'),
            'price_band_max': Decimal('149'),
            'issue_size_cr': Decimal('430.00'),
            'lot_size': 100,
            'min_investment': Decimal('14900'),
            'gmp_percent': Decimal('41.0'),
            'subscription_times': '24.1x',
            'exchange': 'NSE',
            'is_featured': True,
            'description': 'Packaged snacks and ready-to-eat meals brand.',
        },
        {
            'id': 'ipo-datavault-ai',
            'company_name': 'DataVault AI Ltd',
            'symbol': 'DVAIV',
            'sector': 'Technology',
            'status': 'listed',
            'open_date': today - timedelta(days=60),
            'close_date': today - timedelta(days=58),
            'listing_date': today - timedelta(days=45),
            'price_band_min': Decimal('520'),
            'price_band_max': Decimal('548'),
            'issue_size_cr': Decimal('1560.00'),
            'lot_size': 27,
            'min_investment': Decimal('14796'),
            'gmp_percent': Decimal('55.0'),
            'subscription_times': '31.2x',
            'exchange': 'NSE',
            'is_featured': True,
            'description': 'Enterprise data platform with GenAI analytics suite.',
        },
    ]

    for row in rows:
        IpoEvent.objects.update_or_create(id=row['id'], defaults=row)


def unseed_ipo_events(apps, schema_editor):
    IpoEvent = apps.get_model('stocks', 'IpoEvent')
    IpoEvent.objects.filter(id__startswith='ipo-').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_option_trading'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpoEvent',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=160)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('sector', models.CharField(max_length=80)),
                ('status', models.CharField(
                    choices=[
                        ('upcoming', 'Upcoming'),
                        ('open', 'Open Now'),
                        ('closed', 'Closed'),
                        ('listed', 'Listed'),
                    ],
                    default='upcoming',
                    max_length=20,
                )),
                ('open_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('price_band_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_band_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issue_size_cr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lot_size', models.PositiveIntegerField(default=1)),
                ('min_investment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gmp_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('subscription_times', models.CharField(blank=True, max_length=20)),
                ('exchange', models.CharField(default='NSE', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'IPO event',
                'ordering': ['open_date', 'listing_date'],
            },
        ),
        migrations.RunPython(seed_ipo_events, unseed_ipo_events),
    ]
