# Generated by Django 6.0.6 on 2026-06-29 05:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_verified', models.BooleanField(default=False)),
                ('pan_number', models.CharField(blank=True, default='', max_length=10)),
                ('pan_name', models.CharField(blank=True, default='', max_length=120)),
                ('pan_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pan_reference_id', models.CharField(blank=True, default='', max_length=64)),
                ('pan_failure_reason', models.CharField(blank=True, default='', max_length=280)),
                ('pan_verified_at', models.DateTimeField(blank=True, null=True)),
                ('account_holder_name', models.CharField(blank=True, default='', max_length=120)),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=20)),
                ('bank_ifsc', models.CharField(blank=True, default='', max_length=11)),
                ('bank_branch', models.CharField(blank=True, default='', max_length=120)),
                ('bank_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('bank_reference_id', models.CharField(blank=True, default='', max_length=64)),
                ('bank_failure_reason', models.CharField(blank=True, default='', max_length=280)),
                ('bank_verified_at', models.DateTimeField(blank=True, null=True)),
                ('name_at_bank', models.CharField(blank=True, default='', max_length=120)),
                ('name_match_result', models.CharField(blank=True, default='', max_length=40)),
                ('name_match_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('name_match_passed', models.BooleanField(default=False)),
                ('name_match_checked_at', models.DateTimeField(blank=True, null=True)),
                ('overall_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(choices=[('pan', 'PAN'), ('bank', 'Bank'), ('name_match', 'Name Match')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('request_meta', models.JSONField(blank=True, default=dict)),
                ('response_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'step', 'created_at'], name='kyc_verific_user_id_7b0b67_idx')],
            },
        ),
    ]
